version: '3'
services:
  nginx_demo:
    image: nginx.demo
    volumes:
      - ./www/:/var/www/html
    ports:
      - "80:80"
    links:
      - php_demo
  php_demo:
    image: php.demo
    volumes:
      - ./www/:/var/www/html
    ports:
      - "9000:9000"
    links:
      - mysql_demo
  mysql_demo:
    image: mysql.demo
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
