version: '3'
services:
  web:
    image: nginx.demo
    volumes:
      - ./www/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  php:
    image: php.demo
    volumes:
      - ./www/:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mariadb.demo
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
